name: CI - myutils-dev

on:
  pull_request:
    branches: ["develop"]
    paths:
      - "src/**"
      - "Dockerfile"
      - ".github/workflows/ci-dev.yml"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: [self-hosted, oci, dev]

    steps:
      # 1. 체크아웃
      - name: Checkout
        uses: actions/checkout@v4

      # 2. DockerHub 로그인
      - name: Docker login
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # 3. Docker 이미지 빌드 (태그: dev)
      - name: Docker build (Next.js)
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/next-myutils:dev .

      # 4. Docker 이미지 푸시
      - name: Docker push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/next-myutils:dev
